sudo: false

language: node_js
node_js: stable

branches:
  only:
    - master

cache:
  directories:
    - node_modules

install:
  - npm install

jobs:
  include:
    - stage: Verification
      name: 'Tests'
      script: npm test
    - #
      name: 'ESLint'
      script: npm run eslint
    - #
      name: 'Version number'
      script: ./version.sh --can-deploy

    - stage: Deploy
      if: (branch = master AND NOT type = pull_request)
      deploy:
        provider: npm
        skip_cleanup: true
        email: 'artem.kuskis@gmail.com'
        api_key: $NPM_API_KEY
