sudo: false

language: node_js
node_js: stable

branches:
  only:
    - master

cache:
  directories:
    - node_modules

install:
  - npm install

jobs:
  include:
    - stage: tests
      script: npm test
    - stage: checks
      script: npm eslint
    - script: ./version.sh --can-deploy
