sudo: false

language: node_js
node_js: stable

branches:
  only:
    - master

cache:
  directories:
    - node_modules

install:
  - npm install

jobs:
  include:
    - stage: Verification
      name: 'Tests'
      script: npm test
    - #
      name: 'ESLint'
      script: npm run eslint
    - #
      name: 'Version number'
      script: ./version.sh --can-deploy

    - stage: Storybook
      # required to have GH_TOKEN in environment variables
      if: (branch = master AND NOT type = pull_request)
      script: npm run deploy-storybook -- --ci

    - stage: Deploy
      # "deploy npm" doesn't check "return code", that is why it's required to do it manually
      if: (branch = master AND NOT type = pull_request)
      script: echo "//registry.npmjs.org/:_authToken=\${NPM_API_KEY}" > ~/.npmrc && npm run build && npm publish
